#! /bin/bash

#   Add service files to runlevel directory

/bin/cp /etc/init.d/usbmuxd /etc/runlevels/default || true

#   Add service to runlevel

rc-update add usbmuxd default

#   Update services list

rc-update -u
